#!/bin/bash

# Extract the filename without the extension
filename="${PYFILE%.*}"

# Compile the Python script
python3 -m py_compile "$PYFILE"

# Check if compilation was successful
if [ $? -eq 0 ]; then
    echo "Compiling $PYFILE ..."
    mv "__pycache__/${filename}.cpython-*.pyc" "${filename}.pyc"
    rm -rf "__pycache__"
else
    echo "Compilation failed."
    exit 1
fi
